################################
# Direct dependencies

[[constraint]]
  name = "github.com/coreos/etcd"
  revision = "44e1f6f019a98dbea4c8c8def5f077fb0dd83e8a"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.5"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  revision = "bb3d318650d48840a39aa21a027c6630e198e626"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.4.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "5a0f697c9ed9d68fef0116532c6e05cfeae00e55"

[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

[[constraint]]
  name = "github.com/axiomhq/hyperloglog"
  revision = "baba800be098d9f4303352fa6214a933e371e3da"

[[constraint]]
  name = "golang.org/x/sync"
  revision = "fd80eb99c8f653c847d294a001bdf2a3a6f768f5"

[[constraint]]
  name = "golang.org/x/time"
  revision = "6dc17368e09b0e8634d71cac8168d853e869a0c7"
################################

################################
# Transitive dependencies, but to override

[[override]]
  name = "github.com/coreos/bbolt"
  version = "v1.3.1-coreos.6"
################################
