################################
# Direct dependencies


# master branch
[[constraint]]
  name = "github.com/coreos/etcd"
  source = "https://github.com/coreos/etcd"
  revision = "97979dc2450dfb588123d01f7f957f1149e667dc"

# v1.7.5
[[constraint]]
  name = "google.golang.org/grpc"
  source = "https://github.com/grpc/grpc-go"
  revision = "5b3c4e850e90a4cf6a20ebd46c8b32a0a3afcb9e"

[[constraint]]
  name = "github.com/ugorji/go"
  source = "https://github.com/ugorji/go"
  revision = "f3cacc17c85ecb7f1b6a9e373ee85d1480919868"

[[constraint]]
  name = "github.com/axiomhq/hyperloglog"
  source = "https://github.com/axiomhq/hyperloglog"
  revision = "fe9507de02284497dca36b7bb982cb4881a35837"


################################


################################
# Transitive dependencies, and overrides


# v1.3.1-coreos.6
[[override]]
  name = "github.com/coreos/bbolt"
  source = "https://github.com/coreos/bbolt"
  revision = "48ea1b39c25fc1bab3506fbc712ecbaa842c4d2d"

[[override]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  source = "https://github.com/grpc-ecosystem/grpc-gateway"
  revision = "78a473d0e7485950359c782b3c663ee6981eed0c"


################################
