################################
# Direct dependencies


# master branch
[[constraint]]
  name = "github.com/coreos/etcd"
  source = "https://github.com/coreos/etcd"
  revision = "53373fecdd4c02a73814c5fb8a7249c2339a526b"

# v1.7.5
[[constraint]]
  name = "google.golang.org/grpc"
  source = "https://github.com/grpc/grpc-go"
  revision = "5b3c4e850e90a4cf6a20ebd46c8b32a0a3afcb9e"

[[constraint]]
  name = "github.com/ugorji/go"
  source = "https://github.com/ugorji/go"
  revision = "f3cacc17c85ecb7f1b6a9e373ee85d1480919868"


[[constraint]]
  name = "github.com/gogo/protobuf"
  source = "https://github.com/gogo/protobuf"
  revision = "160de10b2537169b5ae3e7e221d28269ef40d311"

[[constraint]]
  name = "github.com/golang/protobuf"
  source = "https://github.com/golang/protobuf"
  revision = "1e59b77b52bf8e4b449a57e6f79f21226d571845"


[[constraint]]
  name = "golang.org/x/sync"
  source = "https://github.com/golang/sync"
  revision = "fd80eb99c8f653c847d294a001bdf2a3a6f768f5"

[[constraint]]
  name = "golang.org/x/time"
  source = "https://github.com/golang/time"
  revision = "6dc17368e09b0e8634d71cac8168d853e869a0c7"


[[constraint]]
  name = "github.com/golang/glog"
  source = "https://github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"


[[constraint]]
  name = "github.com/dustin/go-humanize"
  source = "https://github.com/dustin/go-humanize"
  revision = "02af3965c54e8cacf948b97fef38925c4120652c"

[[constraint]]
  name = "github.com/axiomhq/hyperloglog"
  source = "https://github.com/axiomhq/hyperloglog"
  revision = "fe9507de02284497dca36b7bb982cb4881a35837"


################################


################################
# Transitive dependencies, and overrides


# v1.3.1-coreos.6
[[override]]
  name = "github.com/coreos/bbolt"
  source = "https://github.com/coreos/bbolt"
  revision = "48ea1b39c25fc1bab3506fbc712ecbaa842c4d2d"

# v1.3.0
[[override]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  source = "https://github.com/grpc-ecosystem/grpc-gateway"
  revision = "8cc3a55af3bcf171a1c23a90c4df9cf591706104"


################################

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"
